sudo: required
services:
  - docker

before_install:
  - docker build -t brilliantassociates/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brilliantassociates/react-test npm test -- --coverage

after_success:
  - docker build -t brilliantassociates/multi-client ./client
  - docker build -t brilliantassociates/multi-nginx ./nginx
  - docker build -t brilliantassociates/multi-server ./server
  - docker build -t brilliantassociates/multi-worker ./worker

  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push build images to docker hub
  - docker push brilliantassociates/multi-client
  - docker push brilliantassociates/multi-nginx
  - docker push brilliantassociates/multi-server
  - docker push brilliantassociates/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: multidocker-env-2
  bucket-name: elasticbeanstalk-us-east-1-858193300132
  bucker-path: docker-multi
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY


